### ISSUE TITLE
Documentation tasks - Submission Portal - Parent Issue

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#19]
Add list of documentation that needs to be updated related to the Submission Portal

- [ ] #151
  - Add links to Portal Functionality section
  - Skip for Friday update. Will be done with UI for external data is available.
- [x] Update "[Portal Functionality](https://nmdc-documentation.readthedocs.io/en/latest/howto_guides/submit2nmdc.html)" section text & images
  - This is the text & screen shot for the above video
  - Update text & screen shots
  - Is "Portal Functionality" the best title here?
- [x] Review & update the written "[Submitting to NMDC](https://nmdc-documentation.readthedocs.io/en/latest/howto_guides/submit2nmdc.html)" documentation
- [x] Add find & replace to "[Tools](https://nmdc-documentation.readthedocs.io/en/latest/howto_guides/submit2nmdc.html#tools-and-features)" section text & images)" section
- [x] Review [Tools](https://nmdc-documentation.readthedocs.io/en/latest/howto_guides/submit2nmdc.html#tools-and-features) section for updates. 
  - Better layout options? 
- [ ] #154
  - Skip for Friday release. See issue for future update
- [x] Add any references to GSC?
- [x] https://microbiomedata.org/metadata/
  - Still says "Submission portal Prototype a microbiome metadata submission portal with the ability to capture complex sample relationships and full provenance is under development"
- [x] #126

**Comment by ssarrafan** [comment]
This is on hold until we have a place in new docs area for updating product documentation. Moving to the next sprint.  
@mslarae13 @eecavanna does this sounds ok?

**Comment by ssarrafan** [comment]
We have a way to update documentation now. Shared instructions with Montana. Moving to next sprint.

**Comment by ssarrafan** [comment]
Discussed today at docs squad meeting.  No concerns with getting this done by 1/17/25.

**Comment by mslarae13** [comment]
Merged in my branch, but the images aren't updating? IDK why!

**Comment by eecavanna** [comment]
> Merged in my branch, but the images aren't updating? IDK why!

For my own reference, I think you are referring to this branch ([22-documentation-tasks-field-notes-parent-issue](https://github.com/microbiomedata/docs/tree/22-documentation-tasks-field-notes-parent-issue)) which was merged into `main` via this PR (https://github.com/microbiomedata/docs/pull/125) earlier today.

Will you post an example (e.g. in-page screenshot) of an image that isn't showing what you expected?

**Comment by mslarae13** [comment]
@eecavanna I think the images were just taking a long time to update. Cuz now it looks good! So resolved.
