### ISSUE TITLE
Documentation tasks - Data Portal - Parent Issue

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#20]
Add list of documentation that needs to be updated related to the Data Portal

- [ ] https://nmdc-documentation.readthedocs.io/en/latest/tutorials/nav_data_portal.html text
- [ ] https://nmdc-documentation.readthedocs.io/en/latest/tutorials/nav_data_portal.html video
- [ ] #90
- [ ] https://github.com/microbiomedata/docs/issues/29 - subtask assigned to kitware

**Comment by ssarrafan** [comment]
@aclum any update on this list?  Can this start being actively worked on next sprint?

**Comment by aclum** [comment]
@jkelliher-github  do you still have the script that was used to make the video in https://nmdc-documentation.readthedocs.io/en/latest/tutorials/nav_data_portal.html?

**Comment by aclum** [comment]
There is a PR in for updating the text. I'll need to work with Julia to update the video and that likely won't be done this sprint.

**Comment by aclum** [comment]
@kaelanprime  is reviewing script text. Recording a new video is expected to span past this sprint.

**Comment by kaelanprime** [comment]
Data portal script has been updated to reflect current user interface and terminology, changes will need to be reviewed/accepted by @jkelliher-github

**Comment by ssarrafan** [comment]
@aclum I'm moving this to the next sprint. Assuming this can be completed before holiday break.

**Comment by aclum** [comment]
data portal how to guide text is ready to review.
