### ISSUE TITLE
Documentation tasks - EDGE - Parent Issue

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#21]
Add list of documentation that needs to be updated related to the EDGE

- [x]     https://nmdc-documentation.readthedocs.io/en/latest/tutorials/run_workflows.html 
- [x] https://nmdc-documentation.readthedocs.io/en/latest/howto_guides/run_workflows.html 
- [x] Update video training by mid-January

**Comment by ssarrafan** [comment]
@mflynn-lanl @patrickchain can this issue please be updated with all the EDGE documentation that needs to be kept up to date please?  Would it be reasonable to have someone work on the tasks to update the documentation for EDGE next sprint?

**Comment by ssarrafan** [comment]
@jkelliher-github will be working on the tutorials and how-to-guides and will do this by mid-Jan.

**Comment by ssarrafan** [comment]
@jkelliher-github said the updated videos will also be done by mid-January. Adding this as another item for this issue.

**Comment by ssarrafan** [comment]
Discussed with @jkelliher-github at the docs squad meeting last week. Will move to next sprint. Goal is to have all the updates done by the end of next sprint in time for the mid-January deadline.

FYI @emileyfadrosh @eecavanna

**Comment by ssarrafan** [comment]
@jkelliher-github when will you have the EDGE documentation updated?  
We are planning to cut over to the new docs site by Jan 17th and need this to be done as part  of that. If you need help let me know.

**Comment by ssarrafan** [comment]
@AmitBinf @jkelliher-github @mflynn-lanl is this documentation updated?

**Comment by jkelliher-github** [comment]
Updated for new documentation site

**Comment by ssarrafan** [comment]
@jkelliher-github there appears to be more suggestions from @kaijli 
are those incorporated in your updates?
