### ISSUE TITLE
Documentation tasks - NMDC API - Parent Issue

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#24]
Add to this list of tasks to update, write API documentation:

- [x] ~https://nmdc-documentation.readthedocs.io/en/latest/howto_guides/api_gui.html~
  - @eecavanna crossed this out because the corresponding source file is already listed below
- [ ] https://github.com/microbiomedata/nmdc-server/wiki/Search-API-Docs
  - This is about the Data Portal API (which serves the Data Portal web client and some team members), not the Runtime API (which is used by the general public)
- [x] https://github.com/microbiomedata/NMDC_documentation/blob/main/docs/howto_guides/api_gui.md
- [x] https://nmdc-documentation.readthedocs.io/en/latest/howto_guides/api_gui.html#retrieving-metadata-using-the-find-and-metadata-api-endpoints

**Comment by ssarrafan** [comment]
Checked with Emiley, Lee Ann and Shreyas and Shreyas said he can be the owner of API documentation. Assigning this master issue to @shreddd.  Shreyas please add links and sub-issues to make sure we have all the necessary documentation covered for this topic.  

_Note from Shreyas:  I think the API docs should probably be re-thought since this information is mostly in swagger. I would want to just have a simple how to use the API page, and then fall back on Swagger for the details since it is self documenting. for_

**Comment by ssarrafan** [comment]
@shreddd @eecavanna what's the status of this? Is this in progress? Can you complete this by Friday?  At least the list of sub-tasks? Will you have time to work on this next sprint?

**Comment by ssarrafan** [comment]
Since @shreddd is out of town this week I will add this to the next sprint. 
FYI @eecavanna

**Comment by eecavanna** [comment]
I'll move this to the next sprint.

**Comment by eecavanna** [comment]
@shreddd and I discussed this briefly via Zoom today.

Here are my notes (from during and after that conversation):
1. I'll remove @shreddd  as an assignee on this ticket, making it so I am the only assignee. 
   - I think that will help me track (at a glance) who is "driving" the ticket at the time. @shreddd said that I can transfer the assignment to him in the future if the need arises.
2. I'll update [howto_guides/api_gui.md](https://github.com/microbiomedata/docs/blob/main/content/home/src/howto_guides/api_gui.md) so that it no longer includes parameter-level documentation, which could fall out of sync (i.e. become stale) with respect to Swagger UI and the API, itself.
   - We will refer the reader to Swagger UI for parameter-level documentation.
   - I will add information about logging in and getting an API token.
3. I'll make a Python notebook (MkDocs can render these as HTML, as exemplified [here](https://docs.microbiomedata.org/runtime/nb/queue_and_trigger_data_jobs/)) that demonstrates use of the API to accomplish some task (including logging in).
   - This notebook will live in `[...]/runtime/nb/` and will be part of the MkDocs-powered "Runtime" section of the docs website.

I will move this to next sprint.

**Comment by ssarrafan** [comment]
Discussed today in the doc squad meeting and Eric said he can get these done in time for the cutover 1/17/25.

**Comment by eecavanna** [comment]
I'll finish this up Sunday or Monday.

**Comment by eecavanna** [comment]
FYI, @shreddd, here's a link to the newly-implemented notebook in the context of the `docs.microbiomedata.org` website: https://docs.microbiomedata.org/runtime/nb/api_access_via_python/

**Comment by eecavanna** [comment]
I'll finish the final part of this task tomorrow. That's this part: https://github.com/microbiomedata/docs/issues/165

**Comment by eecavanna** [comment]
This is done. The final subtask was completed via PR https://github.com/microbiomedata/docs/pull/167.
