### ISSUE TITLE
Documentation tasks - FAIR - Parent Issue

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#27]
Add list of tasks to make sure FAIR documentation is updated here

- [x] microbiomedata/issues#983
  - https://github.com/microbiomedata/docs/blob/main/content/nmdc/src/explanation/fair_data.md 
  - https://nmdc-documentation.readthedocs.io/en/latest/explanation/fair_data.html
- [x] https://microbiomedata.org/metadata/
  - Typos in motivation
  - Wordpress
- [x] https://microbiomedata.org/fair/
  - Same text as the readthedocs
  - wordpress will need updated to match the changes in bullet 1
- [x] https://microbiomedata.org/introduction-to-metadata-and-ontologies/
  - Types of metadata figure
  - Wordpress
- [x] https://microbiomedata.org/metadata/overview/
  - "Additional details on processing metadata, coming soon" 
  - Add links to GOLD and ENVO
  - Wordpress
- [x] https://microbiomedata.org/data-standards/
  - Update / add to PIDs   
  - Wordpress

**Comment by ssarrafan** [comment]
@mslarae13 did you find any other links or other FAIR related documentation to add to this list?  Can we add this task to the next sprint?

**Comment by mslarae13** [comment]
yeah add it to the sprint. I did start this, but I will :)

**Comment by mslarae13** [comment]
@ssarrafan  I think I got them all... I think most of the updates needed here are pretty small. We just need to make sure it's eay to navigate.

**Comment by mslarae13** [comment]
@eecavanna Think you can help me find the file that makes this page / text

https://microbiomedata.org/metadata/

**Comment by mslarae13** [comment]
@eecavanna 
I also can't find a file for https://microbiomedata.org/introduction-to-metadata-and-ontologies/

**Comment by eecavanna** [comment]
> What file builds https://microbiomedata.org/metadata/overview/ ?

Everything whose URL starts with `https://microbiomedata.org/` is on the WordPress website. Do you have a user account for logging into https://microbiomedata.org/wp-admin/?

**Comment by mslarae13** [comment]
@eecavanna I don't. Are we planning to leave that in wordpress? Or also provide / capture here?

**Comment by ssarrafan** [comment]
@emileyfadrosh should the FAIR data just be on the website or does it also need to be in the documentation?

**Comment by emileyfadrosh** [comment]
Sorry for the slow reply -- I can take over this ticket. Here are the tasks to be updated: 

- [ ] these two webpages are no longer active, so no need for updates since the content is quite old at this stage and have been replaced:  https://microbiomedata.org/metadata/ & https://microbiomedata.org/metadata/overview/
- [ ] this is a legacy page and because a DOI was issued, we need to have a redirect *only* to the documentation. It will no longer be hosted on the main wordpress site: https://microbiomedata.org/introduction-to-metadata-and-ontologies/
- [ ] I will work with @cmungall to make updates to both the FAIR wordpress text and what will be included in the documentation site -- my preference is to keep both available. 

https://github.com/microbiomedata/issues/issues/983
https://github.com/microbiomedata/docs/blob/main/content/nmdc/src/explanation/fair_data.md
https://nmdc-documentation.readthedocs.io/en/latest/explanation/fair_data.html

Would appreciate input from @mslarae13 when the updates are ready! Thanks :)

**Comment by ssarrafan** [comment]
Thanks @emileyfadrosh for taking this on. I'll move this to the next sprint. Let me know if you need help.

**Comment by emileyfadrosh** [comment]
I've updated the FAIR webpage here with up-to-date information for now: https://microbiomedata.org/fair/

I believe @cmungall is still working on some of the details, so I'll wait to update the documentation further so this and the website do not get too far out of sync. Thanks!

**Comment by ssarrafan** [comment]
@cmungall @emileyfadrosh we are planning for the cutover for the new docs site and having all documentation that's public facing updated by 1/17/25. Can you please complete this issue by next week?

**Comment by emileyfadrosh** [comment]
I created a PR to update the FAIR information to be consistent with the website. @cmungall I assume you don't have time to get anything more done on this front, so I suggest we call it a day and close this out! thanks
