### ISSUE TITLE
Add "Edit this page" links to workflow documentation site

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/docs#84]
This may involve coordinating with the maintainers of the upstream workflow repositories.

- [x] microbiomedata/docs#92
- [x] microbiomedata/docs#93
- [x] microbiomedata/docs#91
- [x] microbiomedata/ReadbasedAnalysis#29
- [x] microbiomedata/ReadsQC#42
- [x] microbiomedata/metaAssembly#30
- [x] microbiomedata/mg_annotation#41
- [x] https://github.com/microbiomedata/metaMAGs/issues/64
- [x] microbiomedata/metaT#40
- [x] microbiomedata/metaT_ReadsQC#10
- [x] microbiomedata/metaT_Assembly#9
- [x] microbiomedata/metaT_ReadCounts#3
- [x] microbiomedata/metaPro#78
- [x] microbiomedata/metaMS#63
- [x] microbiomedata/enviroMS#12

**Comment by eecavanna** [comment]
I identified a solution. I implemented it here: https://github.com/microbiomedata/metaMAGs/pull/65/files. I want to make analogous changes to the other upstream workflow repos.

**Comment by eecavanna** [comment]
At this point, I've implemented the solution on the three relevant files in this `docs` repo and in 5 remote repos. There are still 7 remote repos left to implement it in.

**Comment by eecavanna** [comment]
Done via 13+ PRs (see issue description for a link to each one).
